laurel_sprout: Import fingerprint HIDL
Change-Id: I733eea70dc637fa61c2e3a8036100de7febd71a9
Signed-off-by: TH779 <i@779.moe>

laurel_sprout: Make fingerprint HIDL fully treble compliant

This is more like a hack, also observed in the stock HAL, for pre-P shipped devices
because those have fpdata store path set to /data/system/users/ by the FingerprintService.

Force treble compliant path and thus avoid using data_between_core_and_vendor_violators
attribute:

 > typeattribute hal_fingerprint_default data_between_core_and_vendor_violators;
 > # access to /data/system/users/[0-9]+/fpdata
 > allow hal_fingerprint_default fingerprintd_data_file:dir rw_dir_perms;
 > allow hal_fingerprint_default fingerprintd_data_file:file create_file_perms;

Change-Id: I388f993de7f95fc68007d945f5a9cc975afde120

laurel_sprout: fingerprint: Don't set ro.boot.fpsensor

* It's useless.

Change-Id: I29357c1fbbd7752f3631d9b7f1ce63b61bb41cd0

laurel_sprout: fingerprint: Add Xiaomi fingerprintextension support

Co-authored-by: C457 <android.c357@gmail.com>
Change-Id: Ie9deb0dfcc689034cd3c4b9095e319130ba8d8cd

laurel_sprout: Uprev fingerprint HAL to 2.3

Signed-off-by: TH779 <i@779.moe>
Change-Id: Ia36a9f6f2ed866824a95c2763eae4da15293c448

laurel_sprout: Add support for UDFPS in fingerprint hal

Signed-off-by: TH779 <i@779.moe>
Change-Id: I42cee0efca84800775463daabec4590c4892ca7f

laurel_sprout: fingerprint: move fingerprint manifest to vintf_fragment

laurel_sprout: fingerprint: Call OnFingerUp while postenroll and authenticated

laurel_sprout: fingerprint: Add surfaceflinger extension lib

Change-Id: I6974c03493a1fbabf4ae7c5f491dfeef5d4d6141

laurel_sprout: Enable TARGET_USES_FOD_ZPOS

Change-Id: I5558743ab7f96014aceae0a4e0aea9859a10d5d1
Signed-off-by: DarkDampSquib <andrin.geiger1998@gmail.com>

laurel_sprout: fingerprint: use getInstance() instead

laurel_sprout: Setup UDFPS overlays

 * FOD radius = stock radius value / 2
 * FOD x position = stock x position value + (stock radius value / 2)
 * FOD y position = stock y position value + (stock radius value / 2)
 * FOD enroll progress radius = (stock radius value / 2) + 5

[Skyblueborb]: add framework dimming configs

Change-Id: Ie8add9eb4958bbb55d83d4d2809eb53b1822d15e
Signed-off-by: Sebastiano Barezzi <barezzisebastiano@gmail.com>
Signed-off-by: Skyblueborb <tomaszborbely0710@gmail.com>

laurel_sprout: fingerprint: drop in-kernel handling of changes

This commit is a squash of the following commits:

laurel_sprout: drop in-kernel handling of changes

laurel_sprout: fingerprint: adopted for our laurel_sprout

laurel_sprout: add missing libs

laurel_sprout: added missing `set` method to BiometricsFingerprint

device/xiaomi/laurel_sprout/fingerprint/BiometricsFingerprint.cpp:430:5: error: use of undeclared identifier 'set'
    set(DISPPARAM_PATH, DISPPARAM_HBM_FOD_ON);
    ^
device/xiaomi/laurel_sprout/fingerprint/BiometricsFingerprint.cpp:432:5: error: use of undeclared identifier 'set'
    set(FOD_STATUS_PATH, FOD_STATUS_ON);
    ^
device/xiaomi/laurel_sprout/fingerprint/BiometricsFingerprint.cpp:439:5: error: use of undeclared identifier 'set'
    set(DISPPARAM_PATH, DISPPARAM_HBM_FOD_OFF);
    ^
device/xiaomi/laurel_sprout/fingerprint/BiometricsFingerprint.cpp:441:5: error: use of undeclared identifier 'set'
    set(FOD_STATUS_PATH, FOD_STATUS_OFF);

Co-authored-by: PowerX-NOT <pugalg100@gmail.com>
Co-authored-by: aleeeee1 <pace.alessandro05@protonmail.com>
Signed-off-by: Skyblueborb <tomaszborbely0710@gmail.com>

laurel_sprout: fingerprint: change to in-kernel handling of changes

Revert "laurel_sprout: fingerprint: drop in-kernel handling of changes"

This reverts commit e49f9763fca7d65cb7ab4cd935c4063aaa86daef.

Signed-off-by: Skyblueborb <tomaszborbely0710@gmail.com>

laurel_sprout: fingerprint: Disable fod_status on fod_ui changes

onFingerUp is not called when the finger is kept at the fod area
after it was accepted, which leads to cases where fod_status stays
enabled.

Change-Id: I95da8e12d5cac83dafdfcca286fb4145396a154b
Signed-off-by: Skyblueborb <tomaszborbely0710@gmail.com>

laurel_sprout: fingerprint: Fix UDFPS enrollment and authentication

- Without this screen would light up for just a few seconds, matching would be unreliable and often error out with GF_ERROR_ACQUIRED_IMAGER_DIRTY or GF_ERROR_TOO_FAST

Change-Id: Ibc02d111224dc0921bf91c7b69330dcda2c7dc8f
Signed-off-by: Omkar Chandorkar <gotenksIN@aospa.co>
Signed-off-by: Skyblueborb <tomaszborbely0710@gmail.com>

removed these by accident

Signed-off-by: Skyblueborb <tomaszborbely0710@gmail.com>